apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app.yaml
spec:
  selector:
    matchLabels:
      app: golang-app.yaml
  template:
    metadata:
      labels:
        app: golang-app.yaml
    spec:
      containers:
        - name: golang-app.yaml
          image: durellirsd/golang-argocd:v3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080